function convert_name(arr)
{
    var days = new Array();
    var d=new Date();
    var i;
    for(i = 0;i < 8;i++)
        days[i] = (d.getMonth()+1)+'-'+(d.getDate() - 1 - i);
    switch(arr){
        case 'AA_INSTALL':return 'AA安装';break;
        case 'AA_DOWNLOAD':return 'AA下载';break;
        case 'AA_SHOW':return 'AA展示';break;
        case 'AA_SHOW_RATE':return 'AA展示比昨日';break;
        case 'AA_VIDEO_BFNUM':return 'AA视频播放';break;
        case 'AA_CLICK':return 'AA点击';break;
        case 'CHANNEL':return '频道';break;
        case 'CENTER':return '中心';break;
        case 'DATA_DESC':return '日期';break;
        case 'VV_RATE':return 'VV比昨日';break;
        case 'PV_RATE':return 'PV比昨日';break;
        case 'UV_RATE':return 'UV比昨日';break;
        case 'AA_COVERAGE_RATE':return 'AA广告覆盖率';break;
        case 'VIDEO_SUCCESS_RATE':return '视频播放成功率';break;
        case 'INSTALL_TO_DOWNLOAD':return 'AA安装到AA下载';break;
        case 'DOWNLOAD_TO_SHOW':return 'AA下载到AA展示';break;
        case 'SHOW_TO_VIDEOBF':return 'AA展示到AA视频播放';break;
        case 'VIDEOBF_TO_CLICK':return 'AA视频播放到AA点击';break;
        case 'IV_TO_VV':return 'IV到VV';break;
        case 'VV_TO_CV':return 'VV到CV';break;
        case 'AGO_1_PV':return days[1];break;
        case 'AGO_2_PV':return days[2];break;
        case 'AGO_3_PV':return days[3];break;
        case 'AGO_4_PV':return days[4];break;
        case 'AGO_5_PV':return days[5];break;
        case 'AGO_6_PV':return days[6];break;
        case 'AGO_7_PV':return days[7];break;
        case 'AGO_1_UV':return days[1];break;
        case 'AGO_2_UV':return days[2];break;
        case 'AGO_3_UV':return days[3];break;
        case 'AGO_4_UV':return days[4];break;
        case 'AGO_5_UV':return days[5];break;
        case 'AGO_6_UV':return days[6];break;
        case 'AGO_7_UV':return days[7];break;
        case 'VER':return '版本号';break;
        case 'TODAY_VV':return days[0];break;
        case 'AGO_1_VV':return days[1];break;
        case 'AGO_2_VV':return days[2];break;
        case 'AGO_3_VV':return days[3];break;
        case 'AGO_4_VV':return days[4];break;
        case 'AGO_5_VV':return days[5];break;
        case 'AGO_6_VV':return days[6];break;
        case 'AGO_7_VV':return days[7];break;
        case 'NUM_1':return '激活人数';break;
        case 'T1_KEY_NUM':return days[0];break;
        case 'T2_KEY_NUM':return days[1];break;
        case 'T3_KEY_NUM':return days[2];break;
        case 'T4_KEY_NUM':return days[3];break;
        case 'T5_KEY_NUM':return days[4];break;
        case 'T6_KEY_NUM':return days[5];break;
        case 'T7_KEY_NUM':return days[6];break;
        case 'TODAY_ADSHOW':return days[0];break;
        case 'AGO_1_ADSHOW':return days[1];break;
        case 'AGO_2_ADSHOW':return days[2];break;
        case 'AGO_3_ADSHOW':return days[3];break;
        case 'AGO_4_ADSHOW':return days[4];break;
        case 'AGO_5_ADSHOW':return days[5];break;
        case 'AGO_6_ADSHOW':return days[6];break;
        case 'AGO_7_ADSHOW':return days[7];break;
        case 'DIRECT_UV':return '直接UV';break;
        case 'REFER':return '来源';break;
        case 'VVAUV':return 'VV/UV';break;
        case 'PVAUV':return 'PV/UV';break;
        case 'RETEN_RATE':return '留存率';break;
        case 'date':return '日期';break;
        case 'upload':return '上传';break;
        case 'trans_s_20m':return '转换成功[20m]';break;
        case 'trans_f_20m':return '转换失败[20m]';break;
        case 'trans_g_3d':return '转换进行[3d]';break;
        case 'trans_w_3d':return '转换等待[3d]';break;
        case 'dis_s_20m':return '分发成功[20m]';break;
        case 'dis_f_20m':return '分发失败[20m]';break;
        case 'dis_g_3d':return '分发进行[3d]';break;
        case 'dis_w_3d':return '分发等待[3d]';break;
        case 'DAY0':return '昨天';break;
        case 'DAY1':return '1天前';break;
        case 'DAY2':return '2天前';break;
        case 'DAY3':return '3天前';break;
        case 'DAY4':return '4天前';break;
        case 'DAY5':return '5天前';break;
        case 'DAY6':return '6天前';break;
        case 'DAY7':return '7天前';break;
        default:return arr;
    }
}

